// Auto-generated file. Do not edit manually.
// Generated by: yarn generate-index-dts

declare module "sliftutils/misc/apiKeys" {
    import preact from "preact";
    export declare class APIKeysControl extends preact.Component {
        render(): preact.JSX.Element;
    }
    export declare const getAPIKey: {
        (key: string): Promise<string>;
        clear(key: string): void;
        clearAll(): void;
        forceSet(key: string, value: Promise<string>): void;
        getAllKeys(): string[];
        get(key: string): Promise<string> | undefined;
    };
    export declare function setAPIKey(key: string, value: string): void;
    export declare class ManageAPIKeys extends preact.Component {
        render(): string;
    }

}

declare module "sliftutils/misc/cborx" {
    /// <reference types="node" />
    /// <reference types="node" />
    export declare function cborEncode<T>(value: T): Buffer;
    export declare function cborDecode<T>(buffer: Buffer): T;

}

declare module "sliftutils/misc/environment" {
    export declare function isInChromeExtension(): string | false;
    export declare function isInChromeExtensionBackground(): boolean;
    export declare function isInChromeExtensionContentScript(): boolean | "";
    export declare function isInElectron(): string | false | undefined;
    export declare function triggerIsInBuild(): void;
    export declare function isInBuild(): boolean;
    export declare function isInBrowser(): boolean;

}

declare module "sliftutils/misc/fs" {
    export declare function getAllFiles(folder: string): AsyncIterableIterator<string>;

}

declare module "sliftutils/misc/getSecret" {
    export declare function resetSecret(key: string): void;
    export declare const getSecret: {
        (key: string): Promise<string>;
        clear(key: string): void;
        clearAll(): void;
        forceSet(key: string, value: Promise<string>): void;
        getAllKeys(): string[];
        get(key: string): Promise<string> | undefined;
    };
    export declare function setSecret(key: string, value: string): void;

}

declare module "sliftutils/misc/helpers" {
    export declare function waitForDiskCollectionFlush(): Promise<void>;

}

declare module "sliftutils/misc/https/certs" {
    /// <reference path="node-forge-ed25519.d.ts" />
    /// <reference path="../../storage/storage.d.ts" />
    /// <reference types="node" />
    /// <reference types="node" />
    import * as forge from "node-forge";
    import { MaybePromise } from "socket-function/src/types";
    export declare const CA_NOT_FOUND_ERROR = "18aa7318-f88f-4d2d-b41f-3daf4a433827";
    export declare const identityStorageKey = "machineCA_11";
    export type IdentityStorageType = {
        domain: string;
        certB64: string;
        keyB64: string;
    };
    export interface X509KeyPair {
        domain: string;
        cert: Buffer;
        key: Buffer;
    }
    export declare function getCommonName(cert: Buffer | string): string;
    export declare function createX509(config: {
        domain: string;
        issuer: X509KeyPair | "self";
        lifeSpan: number;
        keyPair: {
            publicKey: forge.Ed25519PublicKey;
            privateKey: forge.Ed25519PrivateKey;
        } | forge.pki.KeyPair;
    }): X509KeyPair;
    export declare function privateKeyToPem(buffer: forge.pki.PrivateKey | forge.Ed25519PrivateKey): string;
    export declare function parseCert(PEMorDER: string | Buffer): forge.pki.Certificate;
    export declare function getPublicIdentifier(PEMorDER: string | Buffer): Buffer;
    export declare const sign: (keyPair: {
        key: string | Buffer;
    }, data: unknown) => string;
    export declare function verify(cert: string, signature: string, data: unknown): void;
    export declare function validateCACert(domain: string, cert: string | Buffer): void;
    export declare function validateCertificate(domain: string, cert: Buffer | string, issuerCert: Buffer | string): void;
    export declare function generateKeyPair(): forge.pki.rsa.KeyPair;
    export declare function generateRSAKeyPair(): forge.pki.rsa.KeyPair;
    export declare function generateTestCA(domain: string): X509KeyPair;
    export declare function createCertFromCA(config: {
        CAKeyPair: X509KeyPair;
    }): X509KeyPair;
    export declare function getMachineId(domainNameOrNodeId: string, domain: string): string;
    export type NodeIdParts = {
        threadId: string;
        machineId: string;
        domain: string;
        port: number;
    };
    export declare function decodeNodeId(nodeId: string, domain: string, allowMissingThreadId?: "allowMissingThreadId"): NodeIdParts | undefined;
    export declare function decodeNodeIdAssert(nodeId: string, domain: string, allowMissingThreadId?: "allowMissingThreadId"): NodeIdParts;
    export declare function encodeNodeId(parts: NodeIdParts): string;
    export declare function setIdentityCARaw(domain: string, json: string): Promise<void>;
    export declare function loadIdentityCA(domain: string): Promise<void>;
    export declare function getIdentityCA(domain: string): X509KeyPair;
    export declare function getIdentityCAPromise(domain: string): MaybePromise<X509KeyPair>;
    export declare function getOwnMachineId(domain: string): string;
    export declare function getOwnThreadId(domain: string): string;
    /** Part of the machineId comes from the publicKey, so we can use it to verify */
    export declare function verifyMachineIdForPublicKey(config: {
        machineId: string;
        publicKey: Buffer;
    }): boolean;
    export declare function getThreadKeyCert(domain: string): X509KeyPair;
    export declare const createTestBrowserKeyCert: {
        (): Promise<X509KeyPair>;
        reset(): void;
        set(newValue: Promise<X509KeyPair>): void;
    };
    export declare function getOwnNodeId(): string;
    export declare function getOwnNodeIdAllowUndefined(): string;

}

declare module "sliftutils/misc/https/dns" {
    export declare function getRecordsRaw(type: string, key: string): Promise<{
        id: string;
        type: string;
        name: string;
        content: string;
        proxied: boolean;
    }[]>;
    export declare function getRecords(type: string, key: string): Promise<string[]>;
    export declare function deleteRecord(type: string, key: string, value: string): Promise<void>;
    /** Removes all existing records (unless the record is already present) */
    export declare function setRecord(type: string, key: string, value: string, proxied?: "proxied"): Promise<void>;
    /** Keeps existing records */
    export declare function addRecord(type: string, key: string, value: string, proxied?: "proxied"): Promise<void>;

}

declare module "sliftutils/misc/https/httpsCerts" {
    /// <reference path="node-forge-ed25519.d.ts" />
    /// <reference path="../../storage/storage.d.ts" />
    /// <reference types="node" />
    /// <reference types="node" />
    import * as forge from "node-forge";
    /** NOTE: We also generate the domain *.domain */
    export declare const getHTTPSCert: {
        (key: string): Promise<{
            key: string;
            cert: string;
        }>;
        clear(key: string): void;
        clearAll(): void;
        forceSet(key: string, value: Promise<{
            key: string;
            cert: string;
        }>): void;
        getAllKeys(): string[];
        get(key: string): Promise<{
            key: string;
            cert: string;
        }> | undefined;
    };
    export declare const getAccountKey: (domain: string) => Promise<string>;
    export declare function parseCert(PEMorDER: string | Buffer): forge.pki.Certificate;
    export declare function normalizeCertToPEM(PEMorDER: string | Buffer): string;
    export declare function generateCert(config: {
        accountKey: string;
        domain: string;
        altDomains?: string[];
    }): Promise<{
        domains: string[];
        key: string;
        cert: string;
    }>;

}

declare module "sliftutils/misc/https/node-forge-ed25519" {


    declare module "node-forge" {
        declare type Ed25519PublicKey = {
            publicKeyBytes: Buffer;
        } & Buffer;
        declare type Ed25519PrivateKey = {
            privateKeyBytes: Buffer;
        } & Buffer;
        class ed25519 {
            static generateKeyPair(): { publicKey: Ed25519PublicKey, privateKey: Ed25519PrivateKey };
            static privateKeyToPem(key: Ed25519PrivateKey): string;
            static privateKeyFromPem(pem: string): Ed25519PrivateKey;
            static publicKeyToPem(key: Ed25519PublicKey): string;
            static publicKeyFromPem(pem: string): Ed25519PublicKey;
        }
    }
}

declare module "sliftutils/misc/https/persistentLocalStorage" {
    import { MaybePromise } from "socket-function/src/types";
    export declare function getKeyStore<T>(appName: string, key: string): {
        get(): MaybePromise<T | undefined>;
        set(value: T | null): MaybePromise<void>;
    };

}

declare module "sliftutils/misc/matchFilter" {
    export declare function matchFilter(filter: {
        value: string;
    }, value: string): boolean;

}

declare module "sliftutils/misc/openrouter" {
    export type MessageHistory = {
        role: "system" | "user" | "assistant";
        content: string;
    }[];
    export type MessageHistory2 = {
        role: "system" | "user" | "assistant";
        content: string | {
            type: "image_url";
            image_url: {
                url: string;
            };
        }[];
    }[];
    export declare function getTotalCost(): number;
    type OpenRouterOptions = {
        apiKey?: string;
        provider?: {
            sort?: "throughput" | "price" | "latency";
            order?: string[];
        };
        reasoningEffort?: "low" | "medium" | "high";
    };
    /** IMPORTANT! Make sure to tell the AI to return yaml. */
    export declare function yamlOpenRouterCall<T>(config: {
        model: string;
        messages: MessageHistory;
        retries?: number;
        options?: OpenRouterOptions;
        onCost?: (cost: number) => void;
        validate?: (response: T) => void;
    }): Promise<T>;
    export declare function simpleAICall(model: string, message: string): Promise<string>;
    /** The message must request the result to be returned in YAML (we automatically parse this and return an object). */
    export declare function simpleAICallTyped<T>(model: string, message: string): Promise<T>;
    export declare function openRouterCall(config: {
        model: string;
        messages: MessageHistory;
        options?: OpenRouterOptions;
        onCost?: (cost: number) => void;
        retries?: number;
    }): Promise<string>;
    export declare function openRouterCallBase(config: {
        model: string;
        messages: MessageHistory2;
        options?: OpenRouterOptions;
        onCost?: (cost: number) => void;
        retries?: number;
    }): Promise<string>;
    export {};

}

declare module "sliftutils/misc/random" {
    export declare function getSeededRandom(seed: number): () => number;
    export declare function shuffle<T>(array: T[], seed: number): T[];
    export declare function secureRandom(): number;

}

declare module "sliftutils/misc/strings" {
    export declare function ellipsize(text: string, maxLength: number): string;

}

declare module "sliftutils/misc/types" {
    export declare function isDefined<T>(value: T | undefined | null): value is T;
    export declare function freezeObject(value: unknown): unknown;
    export declare function deepFreezeObject(value: unknown): void;

}

declare module "sliftutils/misc/yaml" {
    export declare function parseYAML(text: string): unknown;
    export declare function stringifyYAML(value: unknown): string;

}

declare module "sliftutils/misc/yamlBase" {
    export declare const parse: (input: string) => unknown;
    export declare const stringify: (input: unknown) => string;

}

declare module "sliftutils/misc/zip" {
    import { Zip } from "socket-function/src/Zip";
    export { Zip };

}

declare module "sliftutils/render-utils/Anchor" {
    import preact from "preact";
    import { URLParam } from "./URLParam";
    export declare class Anchor extends preact.Component<{
        className?: string;
        params: ([URLParam, unknown] | [string, string])[];
        button?: boolean;
    } & Omit<preact.JSX.HTMLAttributes<HTMLAnchorElement>, "href">> {
        render(): preact.JSX.Element;
    }
    export declare function createLinkRaw(params: ([URLParam, unknown])[]): string;

}

declare module "sliftutils/render-utils/ButtonSelector" {
    import preact from "preact";
    export declare class ButtonSelector<T> extends preact.Component<{
        title?: string;
        value: T;
        options: {
            value: T;
            title: preact.ComponentChild;
            isDefault?: boolean;
            hotkeys?: string[];
        }[];
        onChange: (value: T) => void;
        noPadding?: boolean;
        noDefault?: boolean;
        noUI?: boolean;
        classWrapper?: string;
    }> {
        render(): preact.JSX.Element;
    }

}

declare module "sliftutils/render-utils/DropdownCustom" {
    import preact from "preact";
    import { LengthOrPercentage } from "typesafecss/cssTypes";
    export declare class DropdownCustom<T> extends preact.Component<{
        class?: string;
        optionClass?: string;
        title?: string;
        value: T;
        onChange: (value: T, index: number) => void;
        maxWidth?: LengthOrPercentage;
        options: {
            value: T;
            label: (isOpen: boolean) => preact.ComponentChild;
        }[];
    }> {
        synced: {
            isOpen: boolean;
            tempIndexSelected: number | null;
        };
        onUnmount: (() => void)[];
        componentDidMount(): void;
        componentDidUnmount(): void;
        render(): preact.JSX.Element;
    }

}

declare module "sliftutils/render-utils/FullscreenModal" {
    import preact from "preact";
    export declare function showFullscreenModal(config: {
        contents: preact.ComponentChildren;
        onClose?: () => void;
    }): void;
    export declare class FullscreenModal extends preact.Component<{
        parentState?: {
            open: boolean;
        };
        onCancel?: () => void;
        style?: preact.JSX.CSSProperties;
        outerStyle?: preact.JSX.CSSProperties;
    }> {
        render(): preact.JSX.Element;
    }

}

declare module "sliftutils/render-utils/GenericFormat" {
    import preact from "preact";
    export declare const errorMessage: string;
    export declare const warnMessage: string;
    export type RowType = {
        [columnName: string]: unknown;
    };
    export type FormatContext<RowT extends RowType = RowType> = {
        row?: RowT;
        columnName?: RowT extends undefined ? string : keyof RowT;
    };
    export type JSXFormatter<T = unknown, RowT extends RowType = RowType> = (StringFormatters | `varray:${StringFormatters}` | `link:${string}` | ((value: T, context?: FormatContext<RowT>) => preact.ComponentChild));
    type StringFormatters = ("guess" | "string" | "number" | "timeSpan" | "date" | "error" | "link" | "toSpaceCase");
    export declare function toSpaceCase(text: string): string;
    export declare function formatValue(value: unknown, formatter?: JSXFormatter, context?: FormatContext): preact.ComponentChild;
    export {};

}

declare module "sliftutils/render-utils/Input" {
    import preact from "preact";
    export type InputProps = (preact.JSX.HTMLAttributes<HTMLInputElement> & {
        /** ONLY throttles onChangeValue */
        throttle?: number;
        flavor?: "large" | "small" | "none";
        focusOnMount?: boolean;
        textarea?: boolean;
        /** Update on key stroke, not on blur (just does onInput = onChange, as onInput already does this) */
        hot?: boolean;
        /** Updates arrow keys with modifier behavior to use larger numbers, instead of decimals. */
        integer?: boolean;
        /** Only works with number/integer */
        reverseArrowKeyDirection?: boolean;
        inputRef?: (x: HTMLInputElement | null) => void;
        /** Don't blur on enter key */
        noEnterKeyBlur?: boolean;
        noFocusSelect?: boolean;
        inputKey?: string;
        fillWidth?: boolean;
        autocompleteValues?: string[];
        /** Forces the input to update when focused. Usually we hold updates, to prevent the user's
         *      typing to be interrupted by background updates.
         *      NOTE: "hot" is usually required when using this.
         */
        forceInputValueUpdatesWhenFocused?: boolean;
        onChangeValue?: (value: string) => void;
    });
    export declare class Input extends preact.Component<InputProps> {
        onFocusText: string;
        firstFocus: boolean;
        elem: HTMLInputElement | null;
        lastValue: unknown;
        lastChecked: unknown;
        onChangeThrottle: undefined | {
            throttle: number;
            run: (newValue: string) => void;
        };
        render(): preact.JSX.Element;
    }

}

declare module "sliftutils/render-utils/InputLabel" {
    import preact from "preact";
    export type InputProps = (preact.JSX.HTMLAttributes<HTMLInputElement> & {
        /** ONLY throttles onChangeValue */
        throttle?: number;
        flavor?: "large" | "small" | "none";
        focusOnMount?: boolean;
        textarea?: boolean;
        /** Update on key stroke, not on blur (just does onInput = onChange, as onInput already does this) */
        hot?: boolean;
        /** Updates arrow keys with modifier behavior to use larger numbers, instead of decimals. */
        integer?: boolean;
        /** Only works with number/integer */
        reverseArrowKeyDirection?: boolean;
        inputRef?: (x: HTMLInputElement | null) => void;
        /** Don't blur on enter key */
        noEnterKeyBlur?: boolean;
        noFocusSelect?: boolean;
        inputKey?: string;
        fillWidth?: boolean;
        autocompleteValues?: string[];
        /** Forces the input to update when focused. Usually we hold updates, to prevent the user's
         *      typing to be interrupted by background updates.
         *      NOTE: "hot" is usually required when using this.
         */
        forceInputValueUpdatesWhenFocused?: boolean;
        onChangeValue?: (value: string) => void;
    });
    export type InputLabelProps = Omit<InputProps, "label" | "title"> & {
        label?: preact.ComponentChild;
        number?: boolean;
        /** A number, AND, an integer. Changes behavior arrow arrow keys as well */
        integer?: boolean;
        checkbox?: boolean;
        edit?: boolean;
        alwaysShowPencil?: boolean;
        outerClass?: string;
        maxDecimals?: number;
        percent?: boolean;
        editClass?: string;
        fontSize?: number;
        tooltip?: string;
        fillWidth?: boolean;
        useDateUI?: boolean;
    };
    export declare const startGuessDateRange: number;
    export declare const endGuessDateRange: number;
    export declare class InputLabel extends preact.Component<InputLabelProps> {
        synced: {
            editting: boolean;
            editInputValue: string;
            editUpdateSeqNum: number;
        };
        render(): preact.JSX.Element;
    }
    export declare class InputLabelURL extends preact.Component<InputLabelProps & {
        persisted: {
            value: unknown;
        };
    }> {
        render(): preact.JSX.Element;
    }

}

declare module "sliftutils/render-utils/InputPicker" {
    import preact from "preact";
    export type InputOption<T> = {
        value: T;
        label?: preact.ComponentChild;
        matchText?: string;
    };
    export type FullInputOption<T> = {
        value: T;
        label: preact.ComponentChild;
        matchText: string;
    };
    export declare class InputPickerURL extends preact.Component<{
        label?: preact.ComponentChild;
        options: (string | InputOption<string>)[];
        allowNonOptions?: boolean;
        value: {
            value: string;
        };
    }> {
        render(): preact.JSX.Element;
    }
    export declare class InputPicker<T> extends preact.Component<{
        label?: preact.ComponentChild;
        picked: T[];
        options: InputOption<T>[];
        addPicked: (value: T) => void;
        removePicked: (value: T) => void;
        allowNonOptions?: boolean;
    }> {
        synced: {
            pendingText: string;
            focused: boolean;
        };
        render(): preact.JSX.Element;
    }

}

declare module "sliftutils/render-utils/LocalStorageParam" {
    export declare class LocalStorageParamStr {
        readonly storageKey: string;
        private defaultValue;
        private state;
        lastSetValue: string;
        constructor(storageKey: string, defaultValue?: string);
        forceUpdate(): void;
        get(): string;
        set(value: string): void;
        get value(): string;
        set value(value: string);
    }

}

declare module "sliftutils/render-utils/SyncedController" {
    import { SocketRegistered } from "socket-function/SocketFunctionTypes";
    type RemapFunction<T> = T extends (...args: infer Args) => Promise<infer Return> ? {
        (...args: Args): Return | undefined;
        promise(...args: Args): Promise<Return>;
        refresh(...args: Args): void;
        refreshAll(): void;
        reset(...args: Args): void;
        resetAll(): void;
        isLoading(...args: Args): boolean;
        setCache(cache: {
            args: Args;
            result: Return;
        }): void;
    } : T;
    export declare function getSyncedController<T extends SocketRegistered>(controller: T, config?: {
        /** When a controller call for a write finishes, we refresh all readers.
         *      - Invalidation is global, across all controllers.
         */
        reads?: {
            [key in keyof T["nodes"][""]]?: string[];
        };
        writes?: {
            [key in keyof T["nodes"][""]]?: string[];
        };
    }): {
        (nodeId: string): {
            [fnc in keyof T["nodes"][""]]: RemapFunction<T["nodes"][""][fnc]>;
        } & {
            resetAll(): void;
            refreshAll(): void;
            anyPending(): boolean;
        };
        resetAll(): void;
        refreshAll(): void;
        anyPending(): boolean;
        rerenderAll(): void;
    };
    export {};

}

declare module "sliftutils/render-utils/SyncedLoadingIndicator" {
    import * as preact from "preact";
    export declare class SyncedLoadingIndicator extends preact.Component<{
        controller: {
            anyPending: () => boolean;
        };
    }> {
        render(): preact.JSX.Element | null;
    }

}

declare module "sliftutils/render-utils/Table" {
    import preact from "preact";
    import { JSXFormatter } from "./GenericFormat";
    export type ColumnType<T = unknown, Row extends RowType = RowType> = undefined | null | {
        center?: boolean;
        title?: preact.ComponentChild;
        formatter?: JSXFormatter<T, Row>;
    };
    export type RowType = {
        [columnName: string]: unknown;
    };
    export type ColumnsType = {
        [columnName: string]: ColumnType;
    };
    export type TableType<RowT extends RowType = RowType> = {
        columns: {
            [columnName in keyof RowT]?: ColumnType<RowT[columnName], RowT>;
        };
        rows: RowT[];
    };
    export declare class Table<RowT extends RowType> extends preact.Component<TableType<RowT> & {
        class?: string;
        cellClass?: string;
        initialLimit?: number;
        lineLimit?: number;
        characterLimit?: number;
        excludeEmptyColumns?: boolean;
        getRowFields?: (row: RowT) => preact.JSX.HTMLAttributes<HTMLTableRowElement>;
    }> {
        state: {
            limit: number;
        };
        render(): preact.JSX.Element;
    }

}

declare module "sliftutils/render-utils/URLParam" {
    export declare class URLParam<T = unknown> {
        readonly key: string;
        private defaultValue;
        constructor(key: string, defaultValue?: T);
        valueSeqNum: {
            value: number;
        };
        get(): T;
        set(value: T): void;
        reset(): void;
        getOverride(value: T): [string, string];
        get value(): T;
        set value(value: T);
    }
    export declare function getResolvedParam(param: [URLParam, unknown] | [string, string]): [string, string];
    export declare function batchURLParamUpdate(params: ([URLParam, unknown] | [string, string])[]): void;
    export declare function getCurrentUrl(): string;

}

declare module "sliftutils/render-utils/asyncObservable" {
    export declare function asyncCache<Args, T>(getValue: (args: Args) => Promise<T>): {
        (args: Args): T | undefined;
    };

}

declare module "sliftutils/render-utils/autoMeasure" {
    export declare function runAutoMeasure(): void;

}

declare module "sliftutils/render-utils/colors" {
    export declare const redButton: string;
    export declare const yellowButton: string;
    export declare const greenButton: string;
    export declare const errorMessage: string;
    export declare const warnMessage: string;
    export declare const AnchorClass: string;

}

declare module "sliftutils/render-utils/mobxTyped" {
    export { observable, runInAction, computed, autorun, onBecomeObserved, onBecomeUnobserved } from "mobx";
    export declare function configureMobxNextFrameScheduler(): void;

}

declare module "sliftutils/render-utils/modal" {
    import preact from "preact";
    export declare function showModal(config: {
        contents: preact.ComponentChildren;
        onClose?: () => void;
    }): {
        close: () => void;
    };
    export declare function closeAllModals(): void;

}

declare module "sliftutils/render-utils/niceStringify" {
    export declare const niceStringifyTrue = "";
    export declare const niceStringifyNan = "{NaN}";
    export declare const niceStringifyUndefined = "{Undefined}";
    export declare function niceStringify(value: unknown): string;
    export declare function niceParse(str: string | undefined, noSpecialTrue?: boolean): unknown;

}

declare module "sliftutils/render-utils/observer" {
    import * as preact from "preact";
    import { Reaction } from "mobx";
    export declare function observer<T extends {
        new (...args: any[]): {
            render(): preact.ComponentChild;
            forceUpdate(callback?: () => void): void;
            componentWillUnmount?(): void;
        };
    }>(Constructor: T): {
        new (...args: any[]): {
            reaction: Reaction;
            componentWillUnmount(): void;
            render(...args: any[]): preact.ComponentChild;
            forceUpdate(callback?: () => void): void;
        };
        readonly name: string;
    } & T;

}

declare module "sliftutils/storage/BulkDatabase2/BulkDatabase2" {
    import { BulkDatabaseBase, ReactiveDeps, BulkDatabase2Config, BulkFileInfoListing } from "./BulkDatabaseBase";
    export { BulkDatabaseBase, noopReactiveDeps, bulkDatabase2Timing } from "./BulkDatabaseBase";
    export type { ReactiveDeps, StorageFactory, BulkDatabase2Config, BulkFileDetails, BulkFileEntry, BulkFileInfoListing } from "./BulkDatabaseBase";
    /** Per-column on-disk size info, as reported by getColumnInfo/getReaderInfo. */
    export type BulkColumnInfo = {
        column: string;
        byteSize: number;
    };
    /** A snapshot of the collection's shape (no row data), as reported by getReaderInfo. */
    export type BulkReaderInfo = {
        rowCount: number;
        totalBytes: number;
        keyCount: number;
        sampleKey: string | undefined;
        columns: BulkColumnInfo[];
    };
    /**
     * The full public API of BulkDatabase2 (the static `clearCache()` aside). BulkDatabase2 implements
     * this; an application that just wants to depend on the surface can type against this interface instead
     * of reading the implementation. `T` is the row type and must have a string `key`.
     *
     * Reads resolve every key/column by the latest write-time across all storage tiers. Writes are
     * column-merges: a write/update only changes the columns it includes; columns it omits keep their
     * previous value (clear a column by writing it as `undefined`).
     */
    export interface IBulkDatabase2<T extends {
        key: string;
    }> {
        /** The collection name (its folder under the storage root). */
        readonly name: string;
        /** Write one full row (merging its columns onto any existing row for the key). */
        write(entry: T): Promise<void>;
        /** Write many full rows in one batch. */
        writeBatch(entries: T[]): Promise<void>;
        /** Update only the given columns of an existing key (key required). Warns and no-ops if the key isn't present. */
        update(entry: Partial<T> & {
            key: string;
        }): Promise<void>;
        /** Update many keys' partial columns in one batch. */
        updateBatch(entries: (Partial<T> & {
            key: string;
        })[]): Promise<void>;
        /** Delete a key. */
        delete(key: string): Promise<void>;
        /** Delete many keys in one batch. */
        deleteBatch(keys: string[]): Promise<void>;
        /** All live keys. */
        getKeys(): Promise<string[]>;
        /** One field's value for a key, or undefined if the key/column isn't set or the key is deleted. */
        getSingleField<Column extends keyof T>(key: string, column: Column): Promise<T[Column] | undefined>;
        /**
         * Like getSingleField but returns { key, value, time } (the same shape a getColumn entry has), where
         * time is roughly when the value last changed. undefined only when the key isn't present/live.
         */
        getSingleFieldObj<Column extends keyof T>(key: string, column: Column): Promise<{
            key: string;
            value: T[Column];
            time: number;
        } | undefined>;
        /** A whole column as { key, value, time } for every live key (time ≈ when each value last changed). */
        getColumn<Column extends keyof T>(column: Column): Promise<{
            key: string;
            value: T[Column];
            time: number;
        }[]>;
        /**
         * Synchronous, reactive read of one field. Returns undefined while the base value is still loading
         * (and re-renders once it arrives, under a mobx observer); reflects pending writes immediately.
         */
        getSingleFieldSync<Column extends keyof T>(key: string, column: Column): T[Column] | undefined;
        /** Sync, reactive counterpart of getSingleFieldObj: { key, value, time } once loaded, else undefined. */
        getSingleFieldObjSync<Column extends keyof T>(key: string, column: Column): {
            key: string;
            value: T[Column];
            time: number;
        } | undefined;
        /** Synchronous, reactive read of a whole column ({ key, value, time }). undefined while still loading. */
        getColumnSync<Column extends keyof T>(column: Column): {
            key: string;
            value: T[Column];
            time: number;
        }[] | undefined;
        /**
         * Reactive: whether (key, column) is loaded yet — true once we know the answer (value, absent, or
         * deleted), false while it's still loading. getSingleFieldObjSync returns undefined for BOTH "loading"
         * and "absent", so use this to tell them apart (e.g. show a spinner only when this is false).
         */
        isFieldLoadedSync<Column extends keyof T>(key: string, column: Column): boolean;
        /** Reactive: whether a whole column is loaded yet (see isFieldLoadedSync). */
        isColumnLoadedSync<Column extends keyof T>(column: Column): boolean;
        /**
         * Reactive: true while a merge is rewriting this collection's files (background `maybeMerge` or
         * an explicit `compact`/`merge`/`tryMergeNow`). Becomes false as soon as the new index is swapped
         * in — the deferred-delete cleanup window is NOT counted. Use this in a UI to show a per-database
         * "compacting…" indicator.
         */
        isCompactingSync(): boolean;
        /**
         * Whether a row (key) is currently being watched by some reactive observer (getSingleFieldObjSync /
         * getSingleFieldSync). Lets callers skip per-row work when nothing's watching. Non-reactive query;
         * returns true if the backend can't tell.
         */
        isKeyWatched(key: string): boolean;
        /**
         * Drop all of this collection's in-memory loaded caches and re-trigger every watcher, which re-requests
         * and reloads from disk. Pending un-flushed writes are kept. Per-collection.
         */
        reloadFromDisk(): void;
        /** The columns present on disk and their byte sizes (no row data read). */
        getColumnInfo(): Promise<BulkColumnInfo[]>;
        /** A cheap snapshot of the collection's shape (row/key counts, total bytes, columns) — no row data. */
        getReaderInfo(): Promise<BulkReaderInfo>;
        /**
         * Per-file breakdown of the on-disk files, read fresh from disk each call (latest sizes, including
         * stream files still being appended). `bytes` is the actual on-disk size. Good for showing collection
         * size/fragmentation and deciding whether to call tryMergeNow()/compact().
         */
        getFileInfo(): Promise<BulkFileInfoListing>;
        /** Consolidate on-disk files. Optional to call; the database also does this in the background. */
        compact(): Promise<void>;
        /**
         * Whether this collection's storage is served over the network (a remote server) rather than local
         * disk. Apps can branch on this to adapt to the higher latency. Note: over the network the database
         * skips automatic background compaction by default — call the static
         * `BulkDatabase2.enableNetworkCompaction()` once to opt in.
         */
        isRemote(): Promise<boolean>;
        /**
         * Flush buffered stream writes to disk now. Writes are coalesced and flushed on a ramping delay (to
         * avoid the browser rewriting the whole stream file per write), so a write's promise resolving means
         * "accepted" (in memory + cross-tab), not necessarily "on disk". Call this to force durability — it's
         * also run automatically on tab hide/close and before every merge.
         */
        flush(): Promise<void>;
        /**
         * Run one merge pass now (the same policy the database runs on a timer): consolidate recent
         * fragmentation and dedup a key range if it's worth it. Returns whether it merged anything and
         * whether it bailed because another tab/process holds the merge lock — so a scheduler can call this
         * (e.g. every 30 minutes) and tell "nothing to do" from "someone else is already merging".
         */
        tryMergeNow(): Promise<void>;
        /** Rewrite everything written in [timeLo, timeHi] into fresh key-sorted bulk file(s). Low-level;
         * most callers want compact() or tryMergeNow(). */
        merge(timeLo: number, timeHi: number): Promise<void>;
    }
    export declare class MobxReactiveDeps implements ReactiveDeps {
        private boxes;
        private observed;
        private box;
        observe(signal: string): void;
        invalidate(signal: string): void;
        batch(fn: () => void): void;
        isObserved(signal: string): boolean;
    }
    export declare class BulkDatabase2<T extends {
        key: string;
    }> extends BulkDatabaseBase<T> implements IBulkDatabase2<T> {
        constructor(name: string, config?: BulkDatabase2Config);
    }

}

declare module "sliftutils/storage/BulkDatabase2/BulkDatabaseBase" {
    import type { FileStorage } from "../FileFolderAPI";
    export declare const BULK_ROOT_FOLDER = "bulkDatabases2";
    export declare const bulkDatabase2Timing: {
        streamSealAgeMs: number;
        visibleMergeIntervalMs: number;
        mergeSpacingMs: number;
        firstMergeTriggerFiles: number;
        firstMergeTriggerRangeMs: number;
        streamFoldTriggerRows: number;
        streamFoldTriggerBytes: number;
        streamFileMaxBytes: number;
        streamFoldHardLimitBytes: number;
        writeFlushMaxDelayMs: number;
        fileSetPollIntervalMs: number;
        memoryFlushHeapBytes: number;
        memoryFlushMinCollectionBytes: number;
        memoryFlushThrottleMs: number;
    };
    export interface ReactiveDeps {
        observe(signal: string): void;
        invalidate(signal: string): void;
        batch(fn: () => void): void;
        isObserved?(signal: string): boolean;
    }
    export declare const noopReactiveDeps: ReactiveDeps;
    export type StorageFactory = (path: string) => Promise<FileStorage>;
    export type BulkDatabase2Config = {
        maxTriggerThrottleMs?: number;
    };
    export declare class BulkDatabaseBase<T extends {
        key: string;
    }> {
        readonly name: string;
        protected deps: ReactiveDeps;
        private storageFactory;
        private config;
        constructor(name: string, deps: ReactiveDeps, storageFactory: StorageFactory, config?: BulkDatabase2Config);
        private _reader;
        private get reader();
        private activated;
        private activate;
        private setupVisibilityMergeCheck;
        private subCaches;
        private pendingAppends;
        private flushTimer;
        private flushChain;
        private currentFlushDelay;
        private lastWriteTime;
        private streamFileName;
        private currentStreamFileName;
        private currentStreamFileBytes;
        private mergeInFlight;
        private streamRowsOnDisk;
        private streamBytesOnDisk;
        private fileSetPollTimer;
        private rebuildPromise;
        private rebuildDirty;
        private rebuildOptions;
        private static liveInstances;
        private static memoryWatchdogStarted;
        private static lastMemoryFlushMs;
        private static startMemoryWatchdog;
        static checkMemoryPressure(usedHeapBytes: number): void;
        static clearCache(): void;
        static enableNetworkCompaction(): void;
        storage: {
            (): Promise<FileStorage>;
            reset(): void;
            set(newValue: Promise<FileStorage>): void;
        };
        isRemote(): Promise<boolean>;
        private streamNeedsFold;
        private automaticCompactionAllowed;
        isKeyWatched(key: string): boolean;
        private ensureIndex;
        private triggerRebuild;
        private doOneRebuild;
        reloadFromDisk(): void;
        private pollFileSet;
        private readWithRetry;
        private syncSetup;
        private applyRemote;
        write(entry: T): Promise<void>;
        writeBatch(entries: T[]): Promise<void>;
        delete(key: string): Promise<void>;
        deleteBatch(keys: string[]): Promise<void>;
        private streamAppend;
        flush(): Promise<void>;
        private flushPending;
        private doFlush;
        private getStreamFileName;
        private foldOwnStream;
        update(entry: Partial<T> & {
            key: string;
        }): Promise<void>;
        updateBatch(entries: (Partial<T> & {
            key: string;
        })[]): Promise<void>;
        private listFiles;
        private processMarkers;
        private writeBulkFile;
        private maybeMerge;
        tryMergeNow: () => Promise<void>;
        compact(): Promise<void>;
        merge(timeLo: number, timeHi: number): Promise<void>;
        private readBulkHeader;
        private fileLogicalSize;
        private handleUnreadableFile;
        private mergeFileSet;
        private mergeFileSetInner;
        private canDeleteStream;
        private mergeSpacingDelay;
        private testMergeINTERNAL_DO_NOT_CALL;
        private findDuplicateGroups;
        getSingleField<C extends keyof T>(key: string, column: C): Promise<T[C] | undefined>;
        getSingleFieldObj<C extends keyof T>(key: string, column: C): Promise<{
            key: string;
            value: T[C];
            time: number;
        } | undefined>;
        getColumn<C extends keyof T>(column: C): Promise<{
            key: string;
            value: T[C];
            time: number;
        }[]>;
        getKeys(): Promise<string[]>;
        getSingleFieldSync<C extends keyof T>(key: string, column: C): T[C] | undefined;
        getSingleFieldObjSync<C extends keyof T>(key: string, column: C): {
            key: string;
            value: T[C];
            time: number;
        } | undefined;
        getColumnSync<C extends keyof T>(column: C): {
            key: string;
            value: T[C];
            time: number;
        }[] | undefined;
        isFieldLoadedSync<C extends keyof T>(key: string, column: C): boolean;
        isColumnLoadedSync<C extends keyof T>(column: C): boolean;
        isCompactingSync(): boolean;
        getColumnInfo(): Promise<{
            column: string;
            byteSize: number;
        }[]>;
        getKeyStats(): Promise<{
            rawKeys: number;
            finalKeys: number;
            wastedKeys: number;
            duplication: number;
            readers: number;
        }>;
        getReaderInfo(): Promise<{
            rowCount: number;
            totalBytes: number;
            keyCount: number;
            sampleKey: string | undefined;
            columns: {
                column: string;
                byteSize: number;
            }[];
        }>;
        getFileInfo(): Promise<BulkFileInfoListing>;
    }
    export type BulkFileDetails = {
        keys: string[];
        minTime: number;
        maxTime: number;
    };
    export type BulkFileEntry = {
        name: string;
        type: "bulk" | "stream";
        bytes: number;
        lastModified: number;
        getDetails: () => Promise<BulkFileDetails>;
    };
    export type BulkFileInfoListing = {
        files: BulkFileEntry[];
        count: number;
        totalBytes: number;
    };

}

declare module "sliftutils/storage/BulkDatabase2/BulkDatabaseFormat" {
    /// <reference types="node" />
    /// <reference types="node" />
    export declare const KEY_COLUMN = "key";
    export declare const EMPTY_BUFFER: Buffer;
    export declare const ABSENT: unique symbol;
    export type RawCell = {
        type: number;
        bytes: Buffer;
    };
    export declare const TYPE_ABSENT_TAG = 14;
    export type ColumnIndex = {
        offsets: Uint32Array;
        types: Uint8Array;
        readValueBytes: (startRow: number, endRow: number) => Promise<Buffer>;
    };
    export declare function encodeValue(value: unknown): {
        type: number;
        bytes: Buffer;
    };
    export declare const TARGET_FILE_BYTES: number;
    export type RawRow = {
        key: string;
        time: number;
        cells: Map<string, RawCell>;
    };
    export declare function columnIndexByteLength(rowCount: number): number;
    export declare function assemblePlannedFile(config: {
        valueColumns: {
            name: string;
            blob: Buffer;
        }[];
        keys: string[];
        times: number[];
    }): Buffer;
    export interface BuiltFile {
        buffer: Buffer;
        minKey: string;
        maxKey: string;
        rowCount: number;
    }
    export declare function buildFileBuffer(rows: Record<string, unknown>[], times: number[], targetBytes?: number): BuiltFile[];
    export declare function buildFileBufferRaw(rows: RawRow[], targetBytes?: number): BuiltFile[];
    export type BaseBulkDatabaseReader = {
        name?: string;
        rowCount: number;
        totalBytes: number;
        minTime: number;
        maxTime: number;
        minKey?: string;
        maxKey?: string;
        keys: string[];
        columns: {
            column: string;
            byteSize: number;
        }[];
        keyTimes: Map<string, number>;
        deleteTimes?: Map<string, number>;
        getColumn: (column: string) => Promise<{
            key: string;
            value: unknown;
            time: number;
        }[]>;
        getRawColumn: (column: string) => Promise<Map<string, RawCell>>;
        getColumnIndex: (column: string) => Promise<ColumnIndex>;
        rowOfKey: (key: string) => number | undefined;
        getSingleField: (key: string, column: string) => Promise<{
            value: unknown;
            time: number;
        } | typeof ABSENT>;
    };
    export type BulkHeaderInfo = {
        rowCount: number;
        minTime: number;
        maxTime: number;
        minKey?: string;
        maxKey?: string;
        columns: {
            column: string;
            byteSize: number;
        }[];
    };
    export declare function loadBulkHeader(getRange: (start: number, end: number) => Promise<Buffer>, totalBytes: number): Promise<BulkHeaderInfo>;
    export declare function loadBulkDatabase(config: {
        totalBytes: number;
        getRange: (start: number, end: number) => Promise<Buffer>;
        name?: string;
    }): Promise<BaseBulkDatabaseReader>;

}

declare module "sliftutils/storage/BulkDatabase2/BulkDatabaseMerge" {
    /// <reference types="node" />
    /// <reference types="node" />
    import { BaseBulkDatabaseReader } from "./BulkDatabaseFormat";
    type CopyRun = {
        sourceIdx: number;
        sourceStartRow: number;
        sourceEndRow: number;
        outputByteStart: number;
        byteLength: number;
    };
    type PlannedOutputColumn = {
        name: string;
        offsets: Uint32Array;
        types: Uint8Array;
        dataLength: number;
        runs: CopyRun[];
    };
    export type PlannedOutputFile = {
        keys: string[];
        times: number[];
        minKey: string;
        maxKey: string;
        columns: PlannedOutputColumn[];
        estimatedFileBytes: number;
        sourceCounts: Map<number, number>;
    };
    export type PlannedMergeOutput = {
        name: string;
        minKey: string;
        maxKey: string;
        rowCount: number;
        size: number;
        sources: Map<string, number>;
    };
    export declare function runPlannedMerge(config: {
        sources: BaseBulkDatabaseReader[];
        sourceNames: string[];
        collectionName: string;
        targetFileBytes?: number;
        targetBatchBytes?: number;
        log?: (line: string) => void;
        writeFile: (data: Buffer) => Promise<{
            name: string;
            size: number;
        }>;
    }): Promise<{
        outputs: PlannedMergeOutput[];
        carriedDeletes: Map<string, number>;
        usedSourceNames: Set<string>;
    }>;
    export {};

}

declare module "sliftutils/storage/BulkDatabase2/BulkDatabaseReader" {
    import { LoadedIndex } from "./LoadedIndex";
    import { WriteOverlay } from "./WriteOverlay";
    import type { ReactiveDeps } from "./BulkDatabaseBase";
    declare function nullJoin(a: string, b: string): string;
    export type ReaderConfig = {
        name: string;
        deps: ReactiveDeps;
        maxTriggerThrottleMs?: number;
    };
    export declare class BulkDatabaseReader<T extends {
        key: string;
    }> {
        private readonly cfg;
        constructor(cfg: ReaderConfig);
        index: LoadedIndex<T> | undefined;
        readonly overlay: WriteOverlay;
        private dataGen;
        private columnCache;
        private pendingSignals;
        private triggerTimer;
        private currentTriggerDelay;
        private lastTriggerTime;
        get name(): string;
        get deps(): ReactiveDeps;
        get dataGeneration(): number;
        setIndex(newIndex: LoadedIndex<T>, options?: {
            dropStaleFallback?: boolean;
        }): void;
        applyWrite(key: string, row: Record<string, unknown>, time: number): void;
        applyDelete(key: string, time: number): void;
        isKeyWatched(key: string): boolean;
        isLiveNow(key: string): boolean;
        localTime(key: string): number;
        private compactingCount;
        beginCompaction(): void;
        endCompaction(): void;
        isCompactingSync(): boolean;
        private notifyOverlayMutation;
        getKeys(): Promise<string[]>;
        getColumn<C extends keyof T>(column: C): Promise<{
            key: string;
            value: T[C];
            time: number;
        }[]>;
        getSingleField<C extends keyof T>(key: string, column: C): Promise<T[C] | undefined>;
        getSingleFieldObj<C extends keyof T>(key: string, column: C): Promise<{
            key: string;
            value: T[C];
            time: number;
        } | undefined>;
        getSingleFieldSync<C extends keyof T>(key: string, column: C): T[C] | undefined;
        getSingleFieldObjSync<C extends keyof T>(key: string, column: C): {
            key: string;
            value: T[C];
            time: number;
        } | undefined;
        getColumnSync<C extends keyof T>(column: C): {
            key: string;
            value: T[C];
            time: number;
        }[] | undefined;
        isFieldLoadedSync<C extends keyof T>(key: string, column: C): boolean;
        isColumnLoadedSync<C extends keyof T>(column: C): boolean;
        setEnsureIndex(fn: () => Promise<LoadedIndex<T>>): void;
        private ensureIndexFn;
        private requireIndex;
        private formatInfo;
        private invalidateSignal;
        private flushSignals;
    }
    export declare const READER_SIGNALS: {
        LOAD: string;
        OVERLAY: string;
    };
    export { nullJoin };

}

declare module "sliftutils/storage/BulkDatabase2/LoadedIndex" {
    import type { FileStorage } from "../FileFolderAPI";
    import { BaseBulkDatabaseReader } from "./BulkDatabaseFormat";
    import { GetRange } from "./blockCache";
    import { StreamEntry } from "./streamLog";
    export type BulkFileInfo = {
        fileName: string;
        level: number;
        timestamp: number;
    };
    export type StreamFileInfo = {
        fileName: string;
        timestamp: number;
    };
    export type StreamReaderCacheEntry = {
        readSize: number;
        parsedPos: number;
        entries: StreamEntry[];
    };
    export declare class MissingFileError extends Error {
    }
    export type ResolvedReader = {
        rowCount: number;
        totalBytes: number;
        keys: string[];
        rawKeyCount: number;
        readerCount: number;
        columns: {
            column: string;
            byteSize: number;
        }[];
        keyTimes: Map<string, number>;
        deleteTimes: Map<string, number>;
        getColumn: (column: string) => Promise<{
            key: string;
            value: unknown;
            time: number;
        }[]>;
        getSingleField: (key: string, column: string) => Promise<{
            value: unknown;
            time: number;
        } | undefined>;
    };
    export type SubReaderCaches = {
        bulk: Map<string, BaseBulkDatabaseReader>;
        stream: Map<string, StreamReaderCacheEntry>;
    };
    export declare class LoadedIndex<T extends {
        key: string;
    }> {
        readonly name: string;
        readonly storage: FileStorage;
        readonly bulkFiles: BulkFileInfo[];
        readonly streamFiles: StreamFileInfo[];
        readonly reader: ResolvedReader;
        readonly streamTimes: Map<string, number>;
        readonly streamSizes: Map<string, number>;
        readonly streamRowsOnDisk: number;
        readonly streamBytesOnDisk: number;
        readonly subCaches: SubReaderCaches;
        private constructor();
        readonly keys: Set<string>;
        readonly fileSet: Set<string>;
        private baseColumns;
        private baseColumnsLoading;
        private baseFields;
        private baseFieldsLoading;
        private staleBaseColumns;
        private staleBaseFields;
        get totalBytes(): number;
        get rowCount(): number;
        isLive(key: string): boolean;
        static build<T extends {
            key: string;
        }>(config: {
            name: string;
            storage: FileStorage;
            bulkFiles: BulkFileInfo[];
            streamFiles: StreamFileInfo[];
            subCaches: SubReaderCaches;
            onUnreadableFile?: (file: BulkFileInfo, message: string) => Promise<void>;
        }): Promise<LoadedIndex<T>>;
        inheritStaleFrom(prev: LoadedIndex<T>): void;
        getColumn(column: string): Promise<{
            key: string;
            value: unknown;
            time: number;
        }[]>;
        getSingleField(key: string, column: string): Promise<{
            value: unknown;
            time: number;
        } | undefined>;
        ensureBaseColumn(column: string, onLoaded: () => void): void;
        ensureBaseField(key: string, column: string, onLoaded: () => void): void;
        getBaseColumn(column: string): {
            entries: {
                key: string;
                value: unknown;
                time: number;
            }[];
            fresh: boolean;
        } | undefined;
        getBaseField(key: string, column: string): {
            value: {
                value: unknown;
                time: number;
            } | undefined;
            fresh: boolean;
            loaded: boolean;
        };
        isBaseColumnLoaded(column: string): boolean;
        isBaseFieldLoaded(key: string, column: string): boolean;
        dropLoadedValues(): void;
    }
    export declare function makeRawGetRange(storage: FileStorage, fileName: string): Promise<{
        rawGetRange: GetRange;
        size: number;
    }>;
    export declare function loadFileReader(name: string, storage: FileStorage, f: BulkFileInfo, cache: Map<string, BaseBulkDatabaseReader>): Promise<BaseBulkDatabaseReader>;
    export declare function loadStreamEntries(name: string, storage: FileStorage, streamFiles: StreamFileInfo[], cache: Map<string, StreamReaderCacheEntry>): Promise<{
        entries: {
            time: number;
            fileName: string;
            entry: StreamEntry;
        }[];
        totalBytes: number;
        missing: boolean;
        sizes: Map<string, number>;
    }>;
    export declare function orderStreamEntries(entries: {
        time: number;
        fileName: string;
        entry: StreamEntry;
    }[]): StreamEntry[];

}

declare module "sliftutils/storage/BulkDatabase2/WriteOverlay" {
    export declare const DELETED: unique symbol;
    export type OverlayEntry = {
        time: number;
        value: Record<string, unknown> | typeof DELETED;
    };
    export declare class WriteOverlay {
        private entries;
        get size(): number;
        get(key: string): OverlayEntry | undefined;
        has(key: string): boolean;
        keys(): IterableIterator<string>;
        [Symbol.iterator](): IterableIterator<[string, OverlayEntry]>;
        writeRow(key: string, row: Record<string, unknown>, time: number, wasLive: boolean): {
            invalidatedColumns: Iterable<string> | "all";
        };
        deleteKey(key: string, time: number, wasLive: boolean): {
            invalidatedColumns: Iterable<string> | "all";
        };
        clear(): void;
        sweepCovered(authority: (key: string) => number): void;
        patchColumn(base: {
            key: string;
            value: unknown;
            time: number;
        }[], column: string): {
            key: string;
            value: unknown;
            time: number;
        }[];
    }

}

declare module "sliftutils/storage/BulkDatabase2/blockCache" {
    /// <reference types="node" />
    /// <reference types="node" />
    export type GetRange = (start: number, end: number) => Promise<Buffer>;
    export declare function encodeCompressedBlocks(data: Buffer): Buffer;
    export declare class BlockCache {
        private blocks;
        private indexes;
        clear(): void;
        evict(fileId: string): void;
        private touch;
        private readIndex;
        open(fileId: string, fileSize: number, rawGetRange: GetRange): Promise<{
            uncompressedSize: number;
            getRange: GetRange;
        }>;
        private makeGetRange;
    }
    export declare const blockCache: BlockCache;

}

declare module "sliftutils/storage/BulkDatabase2/mergeLock" {
    import type { FileStorage } from "../FileFolderAPI";
    export declare function tryAcquireMergeLock(collection: string, holderId: string): boolean;
    export declare function releaseMergeLock(collection: string, holderId: string): void;
    export declare function tryAcquireMergeFileLock(storage: FileStorage, holderId: string): Promise<boolean>;
    export declare function startMergeFileLockHeartbeat(storage: FileStorage, holderId: string): () => void;
    export declare function releaseMergeFileLock(storage: FileStorage, holderId: string): Promise<void>;

}

declare module "sliftutils/storage/BulkDatabase2/mergeMarkers" {
    import type { FileStorage } from "../FileFolderAPI";
    export type DeleteMarker = {
        fileName: string;
        deleteFiles: string[];
        replacedBy: string[];
        time: number;
    };
    export declare function isMarkerFile(name: string): boolean;
    export declare function writeDeleteMarker(storage: FileStorage, config: {
        deleteFiles: string[];
        replacedBy: string[];
    }): Promise<void>;
    export declare function readDeleteMarkers(storage: FileStorage, allNames: string[]): Promise<DeleteMarker[]>;
    export declare function markerExclusions(markers: DeleteMarker[]): Set<string>;
    export declare function processDeleteMarkers(name: string, storage: FileStorage, markers: DeleteMarker[], allNames: string[]): Promise<void>;

}

declare module "sliftutils/storage/BulkDatabase2/streamLog" {
    /// <reference types="node" />
    /// <reference types="node" />
    import { BaseBulkDatabaseReader } from "./BulkDatabaseFormat";
    export declare const STREAM_EXTENSION = ".stream";
    export type StreamEntry = {
        time: number;
        row?: Record<string, unknown>;
        deletedKey?: string;
    };
    export declare function frameRows(entries: {
        time: number;
        row: Record<string, unknown>;
    }[]): Buffer;
    export declare function frameDeletes(entries: {
        time: number;
        key: string;
    }[]): Buffer;
    export declare function parseStream(buffer: Buffer): {
        entries: StreamEntry[];
        badBytes: number;
    };
    export declare function streamReaderFromEntries(entries: StreamEntry[], totalBytes: number): {
        reader: BaseBulkDatabaseReader;
        times: Map<string, number>;
    };

}

declare module "sliftutils/storage/BulkDatabase2/syncClient" {
    export type RemoteWrite = {
        key: string;
        time: number;
        deleted?: boolean;
        value?: unknown;
    };
    export declare function isSyncSupported(): boolean;
    export declare function connect(collection: string, onWrite: (write: RemoteWrite) => void, onSeal?: () => void): Promise<RemoteWrite[]>;
    export declare function broadcast(collection: string, write: RemoteWrite): void;
    export declare function broadcastSeal(collection: string): void;

}

declare module "sliftutils/storage/CBORStorage" {
    /// <reference types="node" />
    /// <reference types="node" />
    import { IStorage } from "./IStorage";
    export declare class CBORStorage<T> implements IStorage<T> {
        private storage;
        constructor(storage: IStorage<Buffer>);
        get(key: string): Promise<T | undefined>;
        set(key: string, value: T): Promise<void>;
        remove(key: string): Promise<void>;
        getKeys(): Promise<string[]>;
        getInfo(key: string): Promise<{
            size: number;
            lastModified: number;
        } | undefined>;
        watchResync(callback: () => void): void;
        reset(): Promise<void>;
    }

}

declare module "sliftutils/storage/CachedStorage" {
    import { StorageSync } from "./StorageObservable";
    export declare function newCachedStrStorage<T>(folder: string, getValue: (key: string) => Promise<T>): StorageSync<T>;

}

declare module "sliftutils/storage/DelayedStorage" {
    import { IStorage } from "./IStorage";
    export declare class DelayedStorage<T> implements IStorage<T> {
        private storage;
        constructor(storage: Promise<IStorage<T>>);
        get(key: string): Promise<T | undefined>;
        set(key: string, value: T): Promise<void>;
        remove(key: string): Promise<void>;
        getKeys(): Promise<string[]>;
        getInfo(key: string): Promise<{
            size: number;
            lastModified: number;
        } | undefined>;
        reset(): Promise<void>;
        watchResync(callback: () => void): void;
    }

}

declare module "sliftutils/storage/DiskCollection" {
    /// <reference types="node" />
    /// <reference types="node" />
    import { IStorage, IStorageSync } from "./IStorage";
    import { StorageSync } from "./StorageObservable";
    import { TransactionStorage } from "./TransactionStorage";
    export declare class DiskCollection<T> implements IStorageSync<T> {
        private collectionName;
        private config?;
        static getForceNoPrompt(): boolean;
        static setForceNoPrompt(forceNoPrompt: boolean): void;
        constructor(collectionName: string, config?: {
            writeDelay?: number | undefined;
            cbor?: boolean | undefined;
            noPrompt?: boolean | undefined;
            freeze?: "deep" | "shallow" | undefined;
            beforeWrite?: ((update: {
                newValue: T;
                key: string;
                collection: DiskCollection<T>;
            }) => void) | undefined;
        } | undefined);
        transactionStorage: TransactionStorage | undefined;
        initStorage(): Promise<IStorage<T>>;
        baseStorage: Promise<IStorage<T>>;
        private synced;
        get(key: string): T | undefined;
        getPromise(key: string): Promise<T | undefined>;
        set(key: string, value: T): void;
        remove(key: string): void;
        getKeys(): string[];
        getKeysPromise(): Promise<string[]>;
        getEntries(): [string, T][];
        getValues(): T[];
        getValuesPromise(): Promise<T[]>;
        getInfo(key: string): {
            size: number;
            lastModified: number;
        } | undefined;
        reset(): Promise<void>;
    }
    export declare class DiskCollectionPromise<T> implements IStorage<T> {
        private collectionName;
        private writeDelay?;
        constructor(collectionName: string, writeDelay?: number | undefined);
        initStorage(): Promise<IStorage<T>>;
        private synced;
        get(key: string): Promise<T | undefined>;
        set(key: string, value: T): Promise<void>;
        remove(key: string): Promise<void>;
        getKeys(): Promise<string[]>;
        getInfo(key: string): Promise<{
            size: number;
            lastModified: number;
        } | undefined>;
        reset(): Promise<void>;
    }
    export declare class DiskCollectionRaw implements IStorage<Buffer> {
        private collectionName;
        constructor(collectionName: string);
        initStorage(): Promise<IStorage<Buffer>>;
        private synced;
        get(key: string): Promise<Buffer | undefined>;
        set(key: string, value: Buffer): Promise<void>;
        remove(key: string): Promise<void>;
        getKeys(): Promise<string[]>;
        getInfo(key: string): Promise<{
            size: number;
            lastModified: number;
        } | undefined>;
        reset(): Promise<void>;
    }
    export declare class DiskCollectionRawSynced {
        private collectionName;
        constructor(collectionName: string);
        initStorage(): Promise<IStorage<Buffer>>;
        private synced;
        get(key: string): Buffer | undefined;
        getPromise(key: string): Promise<Buffer | undefined>;
        set(key: string, value: Buffer): void;
        getKeys(): Promise<string[]>;
        getInfo(key: string): Promise<{
            size: number;
            lastModified: number;
        } | undefined>;
        reset(): Promise<void>;
    }
    export declare class DiskCollectionRawBrowser {
        private collectionName;
        constructor(collectionName: string);
        initStorage(): Promise<IStorage<Buffer>>;
        private synced;
        get(key: string): Buffer | undefined;
        getPromise(key: string): Promise<Buffer | undefined>;
        set(key: string, value: Buffer): void;
        getKeys(): Promise<string[]>;
        getInfo(key: string): Promise<{
            size: number;
            lastModified: number;
        } | undefined>;
        reset(): Promise<void>;
    }
    export declare function newFileStorageBufferSyncer(folder?: string): StorageSync<Buffer>;
    export declare function newFileStorageJSONSyncer<T>(folder?: string): StorageSync<T>;

}

declare module "sliftutils/storage/FileFolderAPI" {
    /// <reference types="node" />
    /// <reference types="node" />
    import { IStorageRaw } from "./IStorage";
    import { RemoteOptions } from "./remoteFileStorage";
    declare global {
        interface Window {
            showSaveFilePicker(config?: {
                types: {
                    description: string;
                    accept: {
                        [mimeType: string]: string[];
                    };
                }[];
            }): Promise<FileSystemFileHandle>;
            showDirectoryPicker(): Promise<FileSystemDirectoryHandle>;
            showOpenFilePicker(config?: {
                types: {
                    description: string;
                    accept: {
                        [mimeType: string]: string[];
                    };
                }[];
            }): Promise<FileSystemFileHandle[]>;
        }
        interface FileSystemDirectoryHandle {
            requestPermission(config?: {
                mode: "read" | "readwrite";
            }): Promise<PermissionState>;
        }
    }
    export type FileWrapper = {
        readonly kind: "file";
        readonly name: string;
        getFile(): Promise<{
            size: number;
            lastModified: number;
            arrayBuffer(): Promise<ArrayBuffer>;
            slice(start: number, end: number): {
                arrayBuffer(): Promise<ArrayBuffer>;
            };
        }>;
        createWritable(config?: {
            keepExistingData?: boolean;
        }): Promise<{
            seek(offset: number): Promise<void>;
            write(value: Buffer): Promise<void>;
            close(): Promise<void>;
        }>;
        getURL?(): Promise<string>;
    };
    export type DirectoryWrapper = {
        readonly kind: "directory";
        readonly name: string;
        readonly fullPath?: string;
        readonly isRemote?: boolean;
        removeEntry(key: string, options?: {
            recursive?: boolean;
        }): Promise<void>;
        getFileHandle(key: string, options?: {
            create?: boolean;
        }): Promise<FileWrapper>;
        getDirectoryHandle(key: string, options?: {
            create?: boolean;
        }): Promise<DirectoryWrapper>;
        entries(): AsyncIterableIterator<[string, FileWrapper | DirectoryWrapper]>;
        [Symbol.asyncIterator](): AsyncIterableIterator<[string, FileWrapper | DirectoryWrapper]>;
    };
    export declare function setFileAPIKey(key: string): void;
    export declare class NodeJSFileHandleWrapper implements FileWrapper {
        private filePath;
        constructor(filePath: string);
        readonly kind: "file";
        get name(): string;
        getFile(): Promise<{
            size: number;
            lastModified: number;
            arrayBuffer: () => Promise<ArrayBuffer>;
            slice: (start: number, end: number) => {
                arrayBuffer: () => Promise<ArrayBuffer>;
            };
        }>;
        getURL(): Promise<string>;
        createWritable(config?: {
            keepExistingData?: boolean;
        }): Promise<{
            seek: (offset: number) => Promise<void>;
            write: (value: Buffer) => Promise<void>;
            close: () => Promise<void>;
        }>;
    }
    export declare class NodeJSDirectoryHandleWrapper implements DirectoryWrapper {
        private rootPath;
        constructor(rootPath: string);
        readonly kind: "directory";
        get name(): string;
        get fullPath(): string;
        entries(): AsyncIterableIterator<[string, FileWrapper | DirectoryWrapper]>;
        removeEntry(key: string, options?: {
            recursive?: boolean;
        }): Promise<void>;
        getFileHandle(key: string, options?: {
            create?: boolean;
        }): Promise<FileWrapper>;
        getDirectoryHandle(key: string, options?: {
            create?: boolean;
        }): Promise<DirectoryWrapper>;
        [Symbol.asyncIterator](): AsyncIterableIterator<[string, FileWrapper | DirectoryWrapper]>;
    }
    export declare function usePrivateFileSystem(): void;
    export declare function isPrivateFileSystemActive(): boolean;
    export declare function listPrivateFolders(): Promise<string[]>;
    export declare function pickPrivateFolder(name: string): void;
    export declare const getDirectoryHandle: {
        (): Promise<DirectoryWrapper>;
        reset(): void;
        set(newValue: Promise<DirectoryWrapper>): void;
    };
    export declare const getFileStorageNested: {
        (key: string): Promise<FileStorage>;
        clear(key: string): void;
        clearAll(): void;
        forceSet(key: string, value: Promise<FileStorage>): void;
        getAllKeys(): string[];
        get(key: string): Promise<FileStorage> | undefined;
    };
    export declare const getFileStorageNested2: {
        (key: string): Promise<FileStorage>;
        clear(key: string): void;
        clearAll(): void;
        forceSet(key: string, value: Promise<FileStorage>): void;
        getAllKeys(): string[];
        get(key: string): Promise<FileStorage> | undefined;
    };
    export declare const getFileStorage: {
        (): Promise<FileStorage>;
        reset(): void;
        set(newValue: Promise<FileStorage>): void;
    };
    export declare function resetStorageLocation(): void;
    export type NestedFileStorage = {
        hasKey(key: string): Promise<boolean>;
        getStorage(key: string): Promise<FileStorage>;
        removeStorage(key: string): Promise<void>;
        getKeys(includeFolders?: boolean): Promise<string[]>;
    };
    export type FileStorage = IStorageRaw & {
        folder: NestedFileStorage;
        isRemote?: boolean;
    };
    export declare function wrapHandle(handle: DirectoryWrapper): FileStorage;
    export declare function getFileURL(file: FileWrapper): Promise<string>;
    export declare function disposeFileURL(url: string): void;
    export declare function getRemoteFileStorageFactory(url: string, password: string, options?: RemoteOptions): (pathStr: string) => Promise<FileStorage>;
    export declare function tryToLoadPointer(pointer: string): Promise<DirectoryWrapper | undefined>;

}

declare module "sliftutils/storage/IStorage" {
    /// <reference types="node" />
    /// <reference types="node" />
    export type IStorageSync<T> = {
        get(key: string): T | undefined;
        set(key: string, value: T): void;
        remove(key: string): void;
        getKeys(): string[];
        getValues(): T[];
        getEntries(): [string, T][];
        getInfo(key: string): {
            size: number;
            lastModified: number;
        } | undefined;
        reset(): Promise<void>;
    };
    export type IStorage<T> = {
        get(key: string): Promise<T | undefined>;
        set(key: string, value: T): Promise<void>;
        remove(key: string): Promise<void>;
        getKeys(): Promise<string[]>;
        getInfo(key: string): Promise<undefined | {
            size: number;
            lastModified: number;
        }>;
        reset(): Promise<void>;
        watchResync?: (callback: () => void) => void;
    };
    export type IStorageRaw = {
        get(key: string): Promise<Buffer | undefined>;
        getRange(key: string, config: {
            start: number;
            end: number;
        }): Promise<Buffer | undefined>;
        append(key: string, value: Buffer): Promise<void>;
        set(key: string, value: Buffer): Promise<void>;
        remove(key: string): Promise<void>;
        getKeys(includeFolders?: boolean): Promise<string[]>;
        getInfo(key: string): Promise<undefined | {
            size: number;
            lastModified: number;
        }>;
        reset(): Promise<void>;
    };

}

declare module "sliftutils/storage/IndexedDBFileFolderAPI" {
    import { FileStorage } from "./FileFolderAPI";
    export declare const getFileStorageIndexDB: {
        (): Promise<FileStorage>;
        reset(): void;
        set(newValue: Promise<FileStorage>): void;
    };

}

declare module "sliftutils/storage/JSONStorage" {
    /// <reference types="node" />
    /// <reference types="node" />
    import { IStorage } from "./IStorage";
    export declare class JSONStorage<T> implements IStorage<T> {
        private storage;
        constructor(storage: IStorage<Buffer>);
        get(key: string): Promise<T | undefined>;
        set(key: string, value: T): Promise<void>;
        remove(key: string): Promise<void>;
        getKeys(): Promise<string[]>;
        getInfo(key: string): Promise<{
            size: number;
            lastModified: number;
        } | undefined>;
        watchResync(callback: () => void): void;
        reset(): Promise<void>;
    }

}

declare module "sliftutils/storage/PendingManager" {
    import preact from "preact";
    export declare function setPending(group: string, message: string): void;
    export declare function hasPending(): boolean;
    export declare class PendingDisplay extends preact.Component {
        render(): preact.JSX.Element;
    }

}

declare module "sliftutils/storage/PendingStorage" {
    import { IStorage } from "./IStorage";
    export declare class PendingStorage<T> implements IStorage<T> {
        private pendingGroup;
        private storage;
        pending: Map<string, number>;
        constructor(pendingGroup: string, storage: IStorage<T>);
        get(key: string): Promise<T | undefined>;
        set(key: string, value: T): Promise<void>;
        remove(key: string): Promise<void>;
        getKeys(): Promise<string[]>;
        getInfo(key: string): Promise<{
            size: number;
            lastModified: number;
        } | undefined>;
        private watchPending;
        private updatePending;
        reset(): Promise<void>;
        watchResync(callback: () => void): void;
    }

}

declare module "sliftutils/storage/PrivateFileSystemStorage" {
    /// <reference types="node" />
    /// <reference types="node" />
    import { IStorageRaw } from "./IStorage";
    export declare class PrivateFileSystemStorage implements IStorageRaw {
        private path;
        private rootHandle;
        constructor(path: string);
        private ensureInitialized;
        private directoryExists;
        private getDirectoryHandle;
        private getFileHandle;
        private fileExists;
        get(key: string): Promise<Buffer | undefined>;
        getRange(key: string, config: {
            start: number;
            end: number;
        }): Promise<Buffer | undefined>;
        set(key: string, value: Buffer): Promise<void>;
        append(key: string, value: Buffer): Promise<void>;
        remove(key: string): Promise<void>;
        getKeys(): Promise<string[]>;
        getInfo(key: string): Promise<undefined | {
            size: number;
            lastModified: number;
        }>;
        reset(): Promise<void>;
    }

}

declare module "sliftutils/storage/StorageObservable" {
    import { IStorage, IStorageSync } from "./IStorage";
    export declare const storagePendingAccesses: {
        value: number;
    };
    export declare class StorageSync<T> implements IStorageSync<T> {
        storage: IStorage<T>;
        private config?;
        cached: import("mobx").ObservableMap<string, T | undefined>;
        infoCached: import("mobx").ObservableMap<string, {
            size: number;
            lastModified: number;
        } | undefined>;
        keys: Set<string>;
        synced: {
            keySeqNum: number;
        };
        constructor(storage: IStorage<T>, config?: {
            freeze?: "deep" | "shallow" | undefined;
            beforeWrite?: ((update: {
                newValue: T;
                key: string;
                collection: StorageSync<T>;
            }) => void) | undefined;
        } | undefined);
        get(key: string): T | undefined;
        set(key: string, value: T): void;
        remove(key: string): void;
        private loadedKeys;
        getKeys(): string[];
        getInfo(key: string): {
            size: number;
            lastModified: number;
        } | undefined;
        getValues(): T[];
        getEntries(): [string, T][];
        getPromise(key: string): Promise<T | undefined>;
        private pendingGetKeys;
        getKeysPromise(): Promise<string[]>;
        reload(): void;
        reloadKeys(): void;
        reloadKey(key: string): void;
        reset(): Promise<void>;
    }
    export declare function waitUntilNextLoad(): Promise<void>;

}

declare module "sliftutils/storage/StorageObservableAsync" {
    /** Reruns the code until all StorageSyncs accessed have loaded their values. Not efficient,although will usually be O(values accessed), just due to how loading works (it won't be quadratic). */
    export declare function rerunCodeUntilAllLoaded<T>(code: () => T): Promise<T>;

}

declare module "sliftutils/storage/TransactionStorage" {
    /// <reference types="node" />
    /// <reference types="node" />
    import { IStorage, IStorageRaw } from "./IStorage";
    interface TransactionEntry {
        key: string;
        value: Buffer | undefined;
        isZipped: boolean;
        time: number;
    }
    export declare class TransactionStorage implements IStorage<Buffer> {
        private rawStorage;
        private debugName;
        private writeDelay;
        cache: Map<string, TransactionEntry>;
        private diskFiles;
        private currentChunk;
        private entryCount;
        private static allStorage;
        constructor(rawStorage: IStorageRaw, debugName: string, writeDelay?: number);
        static compressAll(): Promise<void>;
        private resyncCallbacks;
        watchResync(callback: () => void): void;
        private init;
        private getCurrentChunk;
        private updateDiskFileTimestamp;
        private onAddToChunk;
        get(key: string): Promise<Buffer | undefined>;
        set(key: string, value: Buffer): Promise<void>;
        remove(key: string): Promise<void>;
        getInfo(key: string): Promise<{
            size: number;
            lastModified: number;
        } | undefined>;
        private pendingAppends;
        private extraAppends;
        private pendingWrite;
        pushAppend(entry: TransactionEntry): Promise<void>;
        private updatePendingAppends;
        getKeys(): Promise<string[]>;
        checkDisk(): Promise<void>;
        private loadAllTransactions;
        private parseTransactionFile;
        private applyTransactionEntries;
        private readTransactionEntry;
        private serializeTransactionEntry;
        private getHeader;
        private chunkBuffers;
        private compressing;
        private compressTransactionLog;
        reset(): Promise<void>;
    }
    export {};

}

declare module "sliftutils/storage/backblaze" {
    /// <reference types="node" />
    /// <reference types="node" />
    export declare class ArchivesBackblaze {
        private config;
        constructor(config: {
            bucketName: string;
            public?: boolean;
            immutable?: boolean;
            cacheTime?: number;
        });
        private bucketName;
        private bucketId;
        private logging;
        enableLogging(): void;
        private log;
        getDebugName(): string;
        private getBucketAPI;
        private last503Reset;
        private apiRetryLogic;
        get(fileName: string, config?: {
            range?: {
                start: number;
                end: number;
            };
            retryCount?: number;
        }): Promise<Buffer | undefined>;
        set(fileName: string, data: Buffer): Promise<void>;
        del(fileName: string): Promise<void>;
        setLargeFile(config: {
            path: string;
            getNextData(): Promise<Buffer | undefined>;
        }): Promise<void>;
        getInfo(fileName: string): Promise<{
            writeTime: number;
            size: number;
        } | undefined>;
        find(prefix: string, config?: {
            shallow?: boolean;
            type: "files" | "folders";
        }): Promise<string[]>;
        findInfo(prefix: string, config?: {
            shallow?: boolean;
            type: "files" | "folders";
        }): Promise<{
            path: string;
            createTime: number;
            size: number;
        }[]>;
        assertPathValid(path: string): Promise<void>;
        getURL(path: string): Promise<string>;
        getDownloadAuthorization(config: {
            fileNamePrefix?: string;
            validDurationInSeconds: number;
            b2ContentDisposition?: string;
            b2ContentLanguage?: string;
            b2Expires?: string;
            b2CacheControl?: string;
            b2ContentEncoding?: string;
            b2ContentType?: string;
        }): Promise<{
            bucketId: string;
            fileNamePrefix: string;
            authorizationToken: string;
        }>;
    }
    export declare const getArchivesBackblaze: {
        (key: string): ArchivesBackblaze;
        clear(key: string): void;
        clearAll(): void;
        forceSet(key: string, value: ArchivesBackblaze): void;
        getAllKeys(): string[];
        get(key: string): ArchivesBackblaze | undefined;
    };
    export declare const getArchivesBackblazePrivateImmutable: {
        (key: string): ArchivesBackblaze;
        clear(key: string): void;
        clearAll(): void;
        forceSet(key: string, value: ArchivesBackblaze): void;
        getAllKeys(): string[];
        get(key: string): ArchivesBackblaze | undefined;
    };
    export declare const getArchivesBackblazePublicImmutable: {
        (key: string): ArchivesBackblaze;
        clear(key: string): void;
        clearAll(): void;
        forceSet(key: string, value: ArchivesBackblaze): void;
        getAllKeys(): string[];
        get(key: string): ArchivesBackblaze | undefined;
    };
    export declare const getArchivesBackblazePublic: {
        (key: string): ArchivesBackblaze;
        clear(key: string): void;
        clearAll(): void;
        forceSet(key: string, value: ArchivesBackblaze): void;
        getAllKeys(): string[];
        get(key: string): ArchivesBackblaze | undefined;
    };

}

declare module "sliftutils/storage/embeddingBench" {
    export {};

}

declare module "sliftutils/storage/embeddingFormats" {
    export type EmbeddingFormat = "q8g8_2048" | "q8_g16_2048" | "q8_g16_1024" | "float32";
    export declare const EMBEDDING_FORMATS: EmbeddingFormat[];
    export declare const DEFAULT_EMBEDDING_FORMAT: EmbeddingFormat;
    export type QuantType = "q8";
    export type StoredEmbedding = {
        kind: "float32";
        model: string;
        values: Float32Array;
    } | {
        kind: "quant";
        model: string;
        type: QuantType;
        groupSize: number;
        data: Uint8Array;
        scales: Uint8Array;
    };
    export declare function embeddingLength(input: Float32Array | StoredEmbedding): number;
    export declare function releaseFloat32(buffer: Float32Array): void;
    export declare function embeddingToFloat32(input: Float32Array | StoredEmbedding, usePool?: boolean): Float32Array;
    export declare const getCloseness: (a: Float32Array | StoredEmbedding, b: Float32Array | StoredEmbedding) => number;
    export declare function encodeEmbedding(config: {
        input: Float32Array | StoredEmbedding;
        format: EmbeddingFormat;
        model: string;
    }): StoredEmbedding;
    export declare function serializeStoredEmbedding(stored: StoredEmbedding): string;
    export declare function deserializeStoredEmbedding(base64: string): StoredEmbedding;
    export declare function averageEmbeddings(embeddings: StoredEmbedding[], config: {
        format: EmbeddingFormat;
        model: string;
    }): StoredEmbedding;
    export declare function hashEmbedding(stored: StoredEmbedding): string;

}

declare module "sliftutils/storage/faceFramesData" {
    export declare function ensureFaceData(fileName: string, byteLength: number): Promise<string>;

}

declare module "sliftutils/storage/faceFramesServer" {
    export {};

}

declare module "sliftutils/storage/fileSystemPointer" {
    export type FileSystemPointer = string;
    export declare function storeFileSystemPointer(config: {
        mode: "read" | "readwrite";
        handle: FileSystemFileHandle | FileSystemDirectoryHandle;
    }): Promise<FileSystemPointer>;
    export declare function deleteFileSystemPointer(pointer: FileSystemPointer): Promise<void>;
    export declare function getFileSystemPointer(config: {
        pointer: FileSystemPointer;
    }): Promise<{
        onUserActivation(modeOverride?: "read" | "readwrite"): Promise<FileSystemFileHandle | FileSystemDirectoryHandle>;
    } | undefined>;

}

declare module "sliftutils/storage/proxydatabase/Database" {
    export interface Database<Root> {
        readData: <Value>(deref: (root: Root) => Value) => Value | undefined;
        writeData: <Value>(deref: (root: Root) => Value, newValue: Value) => void;
        deleteData: (deref: (root: Root) => unknown) => void;
    }
    export declare function namespaceDatabase<Root, Sub>(database: Database<Root>, into: (root: Root) => Sub): Database<Sub>;

}

declare module "sliftutils/storage/proxydatabase/inMemoryDatabase" {
    import { Database } from "./Database";
    export declare class InMemoryDatabase<Root> implements Database<Root> {
        readCalls: number;
        writeCalls: number;
        deleteCalls: number;
        bytesRead: number;
        bytesWritten: number;
        private root;
        constructor(initial: Root);
        readData<Value>(deref: (root: Root) => Value): Value | undefined;
        writeData<Value>(deref: (root: Root) => Value, newValue: Value): void;
        deleteData(deref: (root: Root) => unknown): void;
    }

}

declare module "sliftutils/storage/proxydatabase/ivfDbCheck" {
    export {};

}

declare module "sliftutils/storage/proxydatabase/ivfEmbeddingDatabase" {
    import { Database } from "./Database";
    import { TransactionSetStore } from "./transactionSet";
    import { StoredEmbedding, EmbeddingFormat } from "../embeddingFormats";
    export type IvfConfig = {
        model: string;
        format: EmbeddingFormat;
        cellTargetSize: number;
    };
    export type IvfEmbeddingRoot = {
        config: IvfConfig;
        count: number;
        flat: TransactionSetStore<StoredEmbedding>;
        byRef: {
            [ref: string]: Uint8Array;
        };
        steps: {
            [step: string]: boolean;
        };
        centroids: TransactionSetStore<StoredEmbedding>;
        cells: {
            [cellId: string]: TransactionSetStore<StoredEmbedding>;
        };
    };
    export type EmbeddingInput = {
        ref: string;
        embedding: StoredEmbedding;
    };
    export type SearchHit = {
        ref: string;
        closeness: number;
    };
    export declare function rebuildStructure(database: Database<IvfEmbeddingRoot>): void;
    export declare function searchEmbeddings(database: Database<IvfEmbeddingRoot>, query: StoredEmbedding, options: {
        probeBudget: number;
        resultCount: number;
    }): SearchHit[] | undefined;
    export declare function lookupEmbeddings(database: Database<IvfEmbeddingRoot>, refs: string[]): Map<string, StoredEmbedding> | undefined;
    export declare function insertEmbeddings(database: Database<IvfEmbeddingRoot>, items: EmbeddingInput[]): undefined;
    export declare function removeEmbeddings(database: Database<IvfEmbeddingRoot>, refs: string[]): void;

}

declare module "sliftutils/storage/proxydatabase/transactionSet" {
    import { Database } from "./Database";
    declare const valueTag: unique symbol;
    export type TransactionSetStore<Value> = {
        [fileNumber: string]: Uint8Array;
        [valueTag]?: Value;
    };
    export declare function transactionRead<Value>(database: Database<TransactionSetStore<Value>>): Map<string, Value> | undefined;
    export declare function replayTransactionStore<Value>(store: TransactionSetStore<Value> | undefined): Map<string, Value>;
    export declare function transactionMutate<Value>(database: Database<TransactionSetStore<Value>>, transactions: {
        key: string;
        value: Value | undefined;
    }[], compactAfterFiles?: number): void;
    export declare function transactionDelete<Value>(database: Database<TransactionSetStore<Value>>): void;
    export {};

}

declare module "sliftutils/storage/remoteFileServer" {
    export declare function generatePassword(wordCount: number): string;
    export type RemoteFileServerOptions = {
        root: string;
        port?: number;
        host?: string;
        password?: string;
        logAccess?: boolean;
    };
    export type RemoteFileServerHandle = {
        port: number;
        password: string;
        url: string;
        close: () => Promise<void>;
    };
    export declare function startRemoteFileServer(options: RemoteFileServerOptions): Promise<RemoteFileServerHandle>;
    export declare function autocompactBulkDatabases(root: string): Promise<void>;
    export declare function runFileHoster(): Promise<void>;

}

declare module "sliftutils/storage/remoteFileStorage" {
    import type { DirectoryWrapper } from "./FileFolderAPI";
    export type RemoteOptions = {
        chunkBytes?: number;
        cacheBytes?: number;
        maxFetchBytes?: number;
        latencyMs?: number;
        stats?: {
            requestCount: number;
            bytesFetched: number;
        };
    };
    export declare function getRemoteDirectoryHandle(url: string, password: string, options?: RemoteOptions): DirectoryWrapper;
    export type RemoteConnectResult = {
        status: "ok";
    } | {
        status: "unauthorized";
    } | {
        status: "unreachable";
        error: string;
    };
    export declare function testRemoteConnection(url: string, password: string, options?: RemoteOptions): Promise<RemoteConnectResult>;

}

declare module "sliftutils/storage/storage" {


    declare module "node-forge" {
        declare type Ed25519PublicKey = {
            publicKeyBytes: Buffer;
        } & Buffer;
        declare type Ed25519PrivateKey = {
            privateKeyBytes: Buffer;
        } & Buffer;
        class ed25519 {
            static generateKeyPair(): { publicKey: Ed25519PublicKey, privateKey: Ed25519PrivateKey };
            static privateKeyToPem(key: Ed25519PrivateKey): string;
            static privateKeyFromPem(pem: string): Ed25519PrivateKey;
            static publicKeyToPem(key: Ed25519PublicKey): string;
            static publicKeyFromPem(pem: string): Ed25519PublicKey;
        }
    }


    interface FileSystemDirectoryHandle {
        [Symbol.asyncIterator](): AsyncIterator<[string, FileSystemFileHandle | FileSystemDirectoryHandle]>;
        requestPermission(config: { mode: "read" | "readwrite" }): Promise<void>;
    }
    interface FileSystemFileHandle {
        getFile(): File;
        createWritable(): FileSystemWritableFileStream;
    }

    interface Window {
        showSaveFilePicker(config?: {
            types: {
                description: string; accept: { [mimeType: string]: string[] }
            }[];
        }): Promise<FileSystemFileHandle>;
        showDirectoryPicker(): Promise<FileSystemDirectoryHandle>;
        showOpenFilePicker(config?: {
            types: {
                description: string; accept: { [mimeType: string]: string[] }
            }[];
        }): Promise<FileSystemFileHandle[]>;
    }
}
