const fs = require("fs");
const path = require("path");

function getAllDtsFiles(dir, fileList = []) {
    const files = fs.readdirSync(dir);

    for (const file of files) {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);

        if (stat.isDirectory()) {
            getAllDtsFiles(filePath, fileList);
        } else if (file.endsWith(".d.ts")) {
            fileList.push(filePath);
        }
    }

    return fileList;
}

function generateIndexDts() {
    const renderUtilsPath = path.join(__dirname, "..", "render-utils");
    const dtsFiles = getAllDtsFiles(renderUtilsPath);

    const modules = dtsFiles
        .map(filePath => {
            const relativePath = path.relative(renderUtilsPath, filePath);
            const withoutExt = relativePath.replace(/\.d\.ts$/, "");
            const modulePath = "sliftutils/render-utils/" + withoutExt.replace(/\\/g, "/");

            const content = fs.readFileSync(filePath, "utf8");
            const indentedContent = content
                .split("\n")
                .map(line => line ? "    " + line : line)
                .join("\n");

            return `declare module "${modulePath}" {\n${indentedContent}\n}`;
        })
        .sort()
        .join("\n\n");

    const outputPath = path.join(__dirname, "..", "index.d.ts");
    const header = `// Auto-generated file. Do not edit manually.\n// Generated by: yarn generate-index-dts\n\n`;

    fs.writeFileSync(outputPath, header + modules + "\n", "utf8");
    console.log(`Generated ${outputPath} with ${dtsFiles.length} module declarations`);
}

generateIndexDts();

